### ISSUE TITLE
Poor performance on Windows 10

### ISSUE THREAD

**Issue by mceachen** [sindresorhus/process-exists#6]
It seems that the current `tasklist` parsing is pretty inefficient. My windows 10 box has ~200 processes running (which seems fairly typical), and depending on the machine speed, the promise is resolved after pegging a CPU for 4 and 8 seconds.

FWIW, linux and mac return within the second.

Debugging information (running with git bash on the windows box):

```tt
$ time tasklist > /dev/null

real    0m0.249s
user    0m0.000s
sys     0m0.015s

$ tasklist | wc -l
223

$ time node -e 'require("process-exists")(744).then(console.dir)'
true

real    0m5.548s
user    0m0.000s
sys     0m0.000s
```

**Comment by mceachen** [comment]
This is (unsurprisingly, I guess) due to `ps-list`/`tasklist`, so I'm moving this over there.

**Comment by mceachen** [comment]
I've opened a PR on tasklist that resolves this issue.

**Comment by sindresorhus** [comment]
Closing as the tasklist PR was merged and released.
